server:
  port: 8080

eureka:
  instance:
    #service id，注册中心服务id
    hostname: localhost
  client:
    service-url: 
      
      #设置与Eureka Server交互的地址，查询服务和注册服务都需要依赖这个地址。默认是http://localhost:8761/eureka ；多个地址可使用 , 分隔。（多server访问地址用于搭建eureka集群环境）
      defaultZone: http://${eureka.instance.hostname}:8080/eureka/
      
      #是否把当前服务注册到eureka注册中心             
      register-with-eureka: false
      
      #是否需要在eureka注册中心中寻找服务
      fetch-registry: false
      
spring:
  application:
    #eureka集群applicationName必须保持一致
    name: eureka-server