server:
  port: 8085

eureka:
  instance:
    #service id，注册中心服务id
    hostname: localhost
  client:
    service-url: 
      
      #设置与Eureka Server交互的地址，查询服务和注册服务都需要依赖这个地址。默认是http://localhost:8761/eureka ；多个地址可使用 , 分隔。（多server访问地址用于搭建eureka集群环境）
      defaultZone: http://${eureka.instance.hostname}:8083/eureka/,
                   http://${eureka.instance.hostname}:8084/eureka/,
                   http://${eureka.instance.hostname}:8085/eureka/
      
      register-with-eureka: true
      fetch-registry: true
      
spring: 
  application:
    #eureka集群applicationName必须保持一致
    name: eureka-server